# Generated by Django 4.0.2 on 2022-03-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=10)),
                ('iemail', models.EmailField(max_length=254)),
                ('iadd', models.CharField(max_length=20)),
                ('igender', models.CharField(max_length=10)),
            ],
        ),
    ]
