# Generated by Django 4.0.2 on 2022-03-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=10)),
                ('upass', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='igender',
        ),
        migrations.AddField(
            model_name='info',
            name='ipass',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='info',
            name='iemail',
            field=models.CharField(max_length=20),
        ),
    ]
