# Generated by Django 4.0.2 on 2022-03-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_login_remove_info_igender_info_ipass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='ipass',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
