# Generated by Django 4.0.2 on 2022-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_info_ipass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='ipass',
            field=models.CharField(default='me', max_length=15),
        ),
    ]
