# Generated by Django 4.0.2 on 2022-03-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_info_ipass'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('upass', models.CharField(max_length=20)),
                ('uadd', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='info',
        ),
        migrations.AlterField(
            model_name='login',
            name='uname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='upass',
            field=models.CharField(max_length=20),
        ),
    ]
