# Generated by Django 4.0.2 on 2022-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_reg_delete_info_alter_login_uname_alter_login_upass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='uname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='upass',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reg',
            name='uemail',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reg',
            name='uname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reg',
            name='upass',
            field=models.CharField(max_length=50),
        ),
    ]
